import assert from 'node:assert/strict'
import { test } from 'node:test'
import { createModelRouteTests, modelRouteTestKey } from '../src/lib/modelRouteTests'
import type { ModelRouteSelection, ModelRouteTestResponse } from '../src/types/modelRouteTest'

const route = (model: string, capability: ModelRouteSelection['capability'] = 'chat'): ModelRouteSelection => ({ provider: 'openrouter', model, capability })
const reply = (selection: ModelRouteSelection, success = true): ModelRouteTestResponse => ({ ...selection, success, duration_ms: 125, message: success ? '测试通过。' : '当前模型不支持此能力。' })
const tick = async () => { await new Promise(resolve => setImmediate(resolve)) }
function deferredProbe() {
  const pending: Array<{ route: ModelRouteSelection; resolve: (value: ModelRouteTestResponse) => void; reject: (error: unknown) => void }> = []
  return { pending, probe: (selection: ModelRouteSelection) => new Promise<ModelRouteTestResponse>((resolve, reject) => { pending.push({ route: selection, resolve, reject }) }) }
}

test('batch deduplicates exact routes, keeps modalities separate, and never exceeds two requests', async () => {
  const { probe, pending } = deferredProbe()
  const controller = createModelRouteTests(probe)
  const a = route('same'), vision = route('same', 'vision'), embedding = route('embedding', 'embedding')
  controller.setSelections([a, a, vision, embedding])
  controller.testAll()
  await tick()
  assert.equal(pending.length, 2)
  assert.equal(controller.getSnapshot().batch?.total, 3)
  assert.equal(controller.getSnapshot().batch?.queued, 1)
  assert.deepEqual(pending.map(item => item.route.capability), ['chat', 'vision'])
  controller.test(a)
  await tick()
  assert.equal(pending.length, 2, 'individual click shares the running batch call')
  pending[0].resolve(reply(a))
  await tick()
  assert.equal(pending.length, 3)
  assert.equal(controller.getSnapshot().batch?.running, 2)
  pending[1].resolve(reply(vision, false))
  pending[2].resolve(reply(embedding))
  await tick()
  assert.deepEqual(controller.getSnapshot().batch, { total: 3, completed: 3, succeeded: 2, failed: 1, cancelled: 0, running: 0, queued: 0, stopped: false })
})

test('changing a draft drops old results and a late response cannot revive them, including A to B to A', async () => {
  const { probe, pending } = deferredProbe()
  const controller = createModelRouteTests(probe)
  const a = route('A'), b = route('B')
  controller.setSelections([a]); controller.test(a)
  await tick()
  controller.setSelections([b])
  assert.deepEqual(controller.getSnapshot().routes, {})
  controller.setSelections([a]); controller.test(a)
  await tick()
  pending[0].resolve(reply(a))
  await tick()
  assert.equal(controller.getSnapshot().routes[modelRouteTestKey(a)].status, 'running')
  pending[1].resolve(reply(a, false))
  await tick()
  assert.equal(controller.getSnapshot().routes[modelRouteTestKey(a)].result?.success, false)
})

test('stopping queued work leaves active calls and completed results intact and supports retry', async () => {
  const { probe, pending } = deferredProbe()
  const controller = createModelRouteTests(probe)
  const choices = ['A', 'B', 'C', 'D'].map(model => route(model))
  controller.setSelections(choices); controller.testAll()
  await tick()
  controller.stopQueued()
  assert.equal(controller.getSnapshot().batch?.cancelled, 2)
  pending[0].resolve(reply(choices[0], false)); pending[1].resolve(reply(choices[1]))
  await tick()
  assert.equal(pending.length, 2)
  assert.equal(controller.getSnapshot().batch?.completed, 2)
  assert.equal(controller.getSnapshot().routes[modelRouteTestKey(choices[1])].result?.success, true)
  controller.test(choices[0])
  await tick()
  assert.equal(pending.length, 3)
  pending[2].resolve(reply(choices[0]))
  await tick()
  assert.equal(controller.getSnapshot().routes[modelRouteTestKey(choices[0])].result?.success, true)
  assert.equal(controller.getSnapshot().batch?.failed, 0, 'batch totals follow a retried route instead of reporting the old failure')
  assert.equal(controller.getSnapshot().batch?.succeeded, 2)
})

test('shared routes survive another row changing while removed queued selections are never sent', async () => {
  const { probe, pending } = deferredProbe()
  const controller = createModelRouteTests(probe)
  const a = route('A'), b = route('B'), c = route('C'), d = route('D')
  controller.setSelections([a, a, b, c]); controller.testAll()
  await tick()
  controller.setSelections([a, d, b])
  pending[0].resolve(reply(a)); pending[1].resolve(reply(b))
  await tick()
  assert.equal(pending.length, 2)
  assert.equal(controller.getSnapshot().routes[modelRouteTestKey(a)].result?.success, true)
  assert.equal(controller.getSnapshot().batch?.cancelled, 1)
  assert.equal(controller.getSnapshot().routes[modelRouteTestKey(c)], undefined)
})

test('unmount cleanup and invalid route responses cannot leak success into a new screen', async () => {
  const { probe, pending } = deferredProbe()
  const controller = createModelRouteTests(probe)
  const a = route('A')
  controller.setSelections([a]); controller.test(a)
  await tick()
  controller.clear(); controller.setSelections([a])
  pending[0].resolve(reply(a))
  await tick()
  assert.deepEqual(controller.getSnapshot().routes, {})
  controller.test(a)
  await tick()
  pending[1].resolve(reply(route('other')))
  await tick()
  assert.equal(controller.getSnapshot().routes[modelRouteTestKey(a)].result?.error_code, 'route_mismatch')
})

test('transport exceptions become safe failures and do not block the queue', async () => {
  const { probe, pending } = deferredProbe()
  const controller = createModelRouteTests(probe)
  const choices = ['A', 'B', 'C'].map(model => route(model))
  controller.setSelections(choices); controller.testAll()
  await tick()
  pending[0].reject(new Error('Authorization: secret'))
  await tick()
  assert.equal(pending.length, 3)
  const failure = controller.getSnapshot().routes[modelRouteTestKey(choices[0])].result!
  assert.equal(failure.success, false)
  assert.doesNotMatch(failure.message, /secret|Authorization/)
  pending[1].resolve(reply(choices[1])); pending[2].resolve(reply(choices[2]))
  await tick()
})
